services:
  my-go-app:
    build: .
    container_name: my-go-app
    depends_on:
      - mongo
      - redis
      - minio
    environment:
      - MONGO_URI=mongodb://mongo_user:Dost0n1k@mongo:27017/soand?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=secretpass
      - MINIO_BUCKET=soandfiles
      - MINIO_USE_SSL=false
    ports:
      - "7777:7777"
    restart: always
    networks:
      - my_network

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: Dost0n1k
      MONGO_INITDB_DATABASE: soand
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my_network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: redis-server --requirepass ""
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - my_network

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=secretpass
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - my_network

volumes:
  mongo_data:
  redis_data:
  minio_data:

networks:
  my_network:
    driver: bridge
